title: Iliiaz and thoughts
url: 'https://ilyusha.io'
baseurl: '' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
# style: styles-3
# style: styles-3
# style: styles-4
# style: styles-5
# style: styles-6

#Profile information
name: Iliiazbek Akhmedov
tagline: #
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
website: ilyusha.io #do not add http://
linkedin: akhmedovi

#Update all the sections by editing the files inside _includes folder.
permalink: pretty
excerpt_separator: <!--more-->
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

kramdown:
  input: GFM

markdown: kramdown
redcarpet:
  extensions: ["tables", "fenced_code_blocks"]
